### PR TITLE
Milestone 2: User interface

### PR DESCRIPTION
**Pull request by simondebbarma**
### Contributors :
- Certil Remy
- Simon Debbarma

---

### Project Requirements

- [x] Suggested branch name: user_interface.
- [x] main.rb file should be responsible for user interaction. In this milestone you should only create content in this file.
- [x] Think about steps needed to play the game:
      - [x] what do you need from player?
      - [x] what do you need to display for player?
- [x] Display prompts for users (hint: puts/print), collect user input (hint: get.chomp) and only mock the basic flow of the game (you can use puts or inline comments to say for example “Now, your move is displayed on the board”).
- [x] Make sure that you can run your game with your executable file and play with the basic flow.
- [x] The final point of this milestone is to make sure that you thought about all actions needed to play Tic Tac Toe. It does not need to work yet - this will be done in the next milestone.

### CODE REVIEW

**Comment by Anna-Myzukina** [comment]
### Pull Request under the review by Anna Muzykina (TSE)

**Comment by Anna-Myzukina** [comment]
## Hi team !  

### Nice job! WOW, project looks! :+1: 

### But your project needs a few changes before it can be approved.


* `[REQUIRED]` game informs player if selected move is invalid
* When I choose for example 10 your game should inform me that this move is invalid
error
*  `[REQUIRED]` game displays board after player move
*  `[REQUIRED]` game informs player if selected move is a winning move
*  `[REQUIRED]` game informs player if selected move is a draw move
* `[REQUIRED]` game repeats all actions for next player's move

##### Implementation details

*  A loop is needed in this game (recommended is `while` but anything else will do) ([OdinProject hint](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/loop.png))
*  Inside loop,  should all actions repeated for each move
*  A loop needs to be terminated at some point (after a winning move or draw to be more specific). It can be done with variable:
loop


*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*
*Happy coding *

**Review by Anna-Myzukina — CHANGES_REQUESTED** [review]
required changes

**Comment by Anna-Myzukina** [comment]
### Let`s fix just a few things and your project can be approved:

*  [REQUIRED] game asks player to select from available moves

*  [REQUIRED] game informs player if selected move is invalid

*  [REQUIRED] game informs player if selected move is a winning move

*  [REQUIRED] game informs player if selected move is a draw move


*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*
*Happy coding *

**Review by Forison — APPROVED** [review]
## Status: Approved💚
## hi Team👋,
Good job👌 on implementing all the changes raised in the previous review. Your project is perfect. Go ahead and merge 💪it.
#### Happy coding💻
#### Addo Forison

**Comment by simondebbarma** [comment]
#  @Forison Thank you very much! 💫

**Pull request merged**
