### PR TITLE
Rspec project Tic-Tact-toe

### PR DESCRIPTION
**Pull request by certilremy**
- [x] Wrap specs for each method in describe block
- [x] Instead of using before_each to define a variable for the test cases, use let.
- [x] Use one it block for each expected behavior. Do not test multiple aspects in one it block.
- [x] Add specs for all public methods you created in Tic Tac Toe project.
- [x] Use existing repositories for Tic Tac Toe add specs and open new Pull Requests.

### CODE REVIEW

**Comment by Anna-Myzukina** [comment]
### Pull Request under the review by Anna Muzykina (TSE)

**Comment by Anna-Myzukina** [comment]
## Hi team! 
Great job so far, however, there are a few things that are missing for this to be approved.


* All the public methods of the classes implemented in project OOP should be tested
screen

* All If specs should cover positive and negative scenarios
screen
* Comments: It’s better to delete commented code. If you need to review a previous version of your code, use git history

screen



### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*


*Happy coding 😄*

**Review by Anna-Myzukina — CHANGES_REQUESTED** [review]
The project needs changes

**Review by fatymahmed — CHANGES_REQUESTED** [review]
### Hi @certilremy @simonpeterdebbarma 
Great job adding more tests 👏👏
However, I think some of your tests are failing, please fix them!.
This is what I get when I run them.
Screenshot


### Kindly make the suggested changes then request for another code review.
### Status: Changes Required 🛑
Feel free to reach out to me on slack (Fatima) if you have any questions, I'd be happy to help.

**Review by Forison — CHANGES_REQUESTED** [review]
### Status Require: changes🛑
## 🙋‍♂️@CERTIL
This what I get after running Rspec🙂
👉 Screenshot from 2020-02-15 05-19-49

## Kindly rectify this error and submit another review
#### Happy coding
#### Addo Forison

**Comment by certilremy** [comment]
> ### Status Require: changes🛑
> ## 🙋‍♂️@Certil
> This what I get after running Rspec🙂
> 👉 Screenshot from 2020-02-15 05-19-49
> 
> ## Kindly rectify this error and submit another review
> #### Happy coding
> #### Addo Forison

Hi , It's say in the Readme run bundle install to install required Gem.

**Comment by Forison** [comment]
> > ### Status Require: changesstop_sign
> > ## raising_hand_man@Certil
> > This what I get after running Rspecslightly_smiling_face
> > point_right Screenshot from 2020-02-15 05-19-49
> > ## Kindly rectify this error and submit another review
> > #### Happy coding
> > #### Addo Forison
> 
> Hi , It's say in the Readme run bundle install to install required Gem.

sorry for earlier

**Review by Forison — APPROVED** [review]
# Status: Approved💚
# sorry for earlier😔,
Your project is good💪
# Go ahead and merge

**Comment by certilremy** [comment]
> # Status: Approved💚
> # sorry for earlier😔,
> Your project is good💪
> 
> # Go ahead and merge

No problem it could happen to anyone. Thank you for reviewing our project out of business 
time.

**Pull request merged**
